# Generated by Django 4.0.3 on 2022-04-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_customer_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='type',
            new_name='typee',
        ),
    ]
