# Generated by Django 4.0.3 on 2022-03-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cím')),
                ('releaseDate', models.DateField(verbose_name='Bemutató dátuma')),
                ('rating', models.FloatField(verbose_name='Értékelés')),
            ],
        ),
    ]
