# Generated by Django 4.0.3 on 2022-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=40, verbose_name='Tananyag Név')),
                ('description', models.TextField(verbose_name='Tananyag Leírás')),
                ('instructor', models.CharField(max_length=40, verbose_name='Tanár')),
                ('rates', models.FloatField(verbose_name='Értékelés')),
            ],
        ),
    ]
